language: node_js

node_js:
  - "6"

branches:
  except:
    - gh-pages

cache:
  directories:
  - node_modules
  - bower_components

env:
  global:
    - DEPLOY_BRANCH="master"
    - TARGET_BRANCH="gh-pages"
    - SOURCE_DIR="docs"
    - GIT_NAME="Travis-CI"
    - GIT_EMAIL="deploy@travis-ci.org"
    - GITHUB_REF="github.com/Bruce17/polymer-feedback-form.git"
    # Will be injected by Travis itself.
    #- GITHUB_TOKEN=""

before_script:
  - npm install -g bower
  - npm install
  - bower install

script:
  # Lint files
#  - npm run lint
  # Build polymer files
  - npm run build

after_success:
  # Deploy results to "gh-pages" branch
  - npm run deploy:ci